---
- name: include ufw role
  include_role:
    name: ufw

- name: enable ufw for blackbox_exporter
  ufw:
    comment: 'Prometheus blackbox_exporter'
    rule: allow
    src: '{{ item }}'
    proto: tcp
    port: '{{ prometheus_blackbox_exporter_listen_port }}'
    direction: in
  loop: '{{ prometheus_blackbox_exporter_src_access }}'
...
